name: imitation_learning
dependencies:
    - python=3.6
    - numpy
    - matplotlib
    - jupyter
    - h5py
    - flask-socketio
    - scikit-learn
    - tensorflow=1.14
    - black
    - pylint
    - pip
    - pip:
        - eventlet
        - opencv-python
